export type PRODUCT_OWNERSHIP_TYPE = 'owner' | 'consumer'
export type QUOTATION_PRODUCT_NAME_TYPE = 'custom_product' | 'real_product'

export type UnitOfMeasurement =
  | 'kg'
  | 'lb'
  | 'm'
  | 'yd'
  | 'ft'
  | 'in'
  | 'cm'
  | 'sq.m'
  | 'sq.ft'
  | 'sq.in'
  | 'cu.m'
  | 'cu.ft'
  | 'cu.in'

export type ItemCollectionType =
  | 'set(s)'
  | 'piece(s)'
  | 'pack(s)'
  | 'carton(s)'
  | 'box(es)'
  | 'bottle(s)'
  | 'truck(s)'
  | 'container(s)'
  | 'dozen(s)'
  | 'wrap(s)'
  | 'roll(s)'

export type DiscountType = 'percentage' | 'number'
export type RoundingType = 'none' | 'nearest' | 'down' | 'up'
export type ThousandSeparator = 'comma' | 'period' | 'none' | 'space'
